name: CI

on:
  push:
    branches: [main]
    tags: ['*']

  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          make -j2

      - name: Debug
        run: |
          cd demo
          make
          # ./main debug
          ./example_var_init_builder debug
          ./example_var_init_builder
          ./example_var_init

      # - name: Tests
      #   run: |
      #     cd demo
      #     make
      #     ./rere.py replay test.list

      - name: Linux archive
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
        run: |
          name="libqbe-linux-x86_64"

          mkdir $name
          mv lib include $name
          zip -r $name.zip $name

      - name: macOS archive
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'macos-latest'
        run: |
          name="libqbe-macos-arm64"

          mkdir $name
          mv lib include $name
          zip -r $name.zip $name

      - name: Upload build artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            libqbe-linux-x86_64.zip
            libqbe-macos-arm64.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ubuntu-latest-build/libqbe-linux-x86_64.zip
            macos-latest-build/libqbe-macos-arm64.zip
