name: CI

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos
            arch: x86_64
            runner: macos-13
          - os: macos
            arch: arm64
            runner: macos-latest
          - os: ubuntu
            arch: x86_64
            runner: ubuntu-latest
          - os: ubuntu
            arch: arm64
            runner: ubuntu-latest

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v3

      - name: Show info
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "Arch: ${{ matrix.arch }}"
          echo "Runner: ${{ matrix.runner }}"
          uname -m

      - name: Build
        run: make -j$(nproc)

      - name: Test demo
        run: |
          cd demo
          make
          ./main

      - name: Linux archive
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
        run: |
          name="libqbe-linux-${{ matrix.arch }}"

          mkdir $name
          mv lib include $name
          zip -r $name.zip $name

      - name: macOS archive
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'macos-latest'
        run: |
          name="libqbe-macos-${{ matrix.arch }}"

          mkdir $name
          mv lib include $name
          zip -r $name.zip $name

      - name: Upload build artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-build
          path: |
            libqbe-linux-${{ matrix.arch }}.zip
            libqbe-macos-${{ matrix.arch }}.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ubuntu-latest-x86_64-build/libqbe-linux-x86_64.zip
            ubuntu-latest-arm64-build/libqbe-linux-arm64.zip
            macos-latest-x86_64-build/libqbe-macos-x86_64.zip
            macos-latest-arm64-build/libqbe-macos-arm64.zip
